### ISSUE TITLE
Fix NPM Package Versions

### ISSUE THREAD

**Issue by zubietaroberto** [Electronic-Signatures-Industries/xdv-document-signer#13]
Some of the packages seem to be using new versions that break the files while uploading them to IPFS. We must upgrade and fix those packages to make sure that the uploads are done correctly. This is the preliminary list of packages that seem to be involved:

"3id-did-provider": "0.1.2",
"dids": "1.1.1",
"ipfs-core": "0.3.1",
"ipfs-http-client": "48.1.3",
"ipfs-repo": "7.0.0",
"ipld": "0.28.0",
"ipld-dag-cbor": "0.15.3",
"jsrsasign": "^8.0.20",
"key-did-provider-ed25519": "1.0.0",
"multicodec": "1.0.4",
"multiformats": "3.0.3",

**Comment by molekilla** [comment]
@zubietaroberto `smartcard_rsa` superseded main and was upgraded and trim. thanks
